import os
import time

from dotenv import load_dotenv
from google import genai
from google.genai import errors


# ============================================================
# LegalEase - AI Legal Document Generation Engine
# ============================================================

# Load environment variables from .env
load_dotenv()


# Get Gemini API key
api_key = os.getenv("GEMINI_API_KEY")

if not api_key:
    raise ValueError(
        "GEMINI_API_KEY is missing from .env"
    )


# Create Gemini client
client = genai.Client(api_key=api_key)


def generate_legal_document(document_type, details):
    """
    Generate a professional legal document using Gemini.
    """

    prompt = f"""
You are the AI legal document generation engine for LegalEase.

Your task is to generate a professional, well-structured
legal document based on the information provided by the user.

DOCUMENT TYPE:
{document_type}

USER-PROVIDED INFORMATION:
{details}


IMPORTANT INSTRUCTIONS:

1. Generate a complete and professionally structured document.

2. Use clear, formal and professional legal language.

3. Use appropriate headings and numbered sections.

4. Include relevant information such as:
   - Parties
   - Effective date
   - Purpose
   - Definitions
   - Rights and obligations
   - Terms and conditions
   - Confidentiality where applicable
   - Termination where applicable
   - Governing law where applicable
   - Signatures

5. Do NOT invent important personal information.

6. If required information is missing, use placeholders such as:
   [PARTY NAME]
   [ADDRESS]
   [DATE]
   [JURISDICTION]

7. Keep the document logically organized and easy to edit.

8. Do not use unnecessary explanations outside the document.

9. At the end of the document, include this disclaimer:

Disclaimer:
This document is an automated template generated by the
LegalEase document generation engine for informational purposes
only. It does not constitute formal legal advice. Laws vary by
jurisdiction; please consult a qualified attorney or legal
counsel to ensure this document meets your specific requirements
and complies with applicable laws.

10. The generated document will later be exported to DOCX and PDF,
so keep the formatting clean and professional.
"""


    # --------------------------------------------------------
    # Retry mechanism for temporary Gemini server errors
    # --------------------------------------------------------

    max_attempts = 3

    for attempt in range(1, max_attempts + 1):

        try:

            response = client.models.generate_content(
                model="gemini-3.8-flash",
                contents=prompt
            )

            if not response.text:
                raise ValueError(
                    "Gemini returned an empty response."
                )

            return response.text


        except errors.ServerError as error:

            if attempt < max_attempts:

                wait_time = 5 * (2 ** (attempt - 1))

                print(
                    f"\nGemini server is temporarily unavailable."
                )

                print(
                    f"Retry attempt {attempt}/{max_attempts - 1}"
                )

                print(
                    f"Waiting {wait_time} seconds...\n"
                )

                time.sleep(wait_time)

            else:

                print(
                    "\nGemini server is still unavailable "
                    "after multiple attempts."
                )

                raise error


# ============================================================
# Test LegalEase AI Engine
# ============================================================

if __name__ == "__main__":

    document = generate_legal_document(

        "Non-Disclosure Agreement (NDA)",

        """
Party A:
ABC Technologies Pvt. Ltd.

Party B:
John Mathew

Effective Date:
28 September 2026

Purpose:
Party B will receive confidential business and technical
information from Party A.

Confidentiality Period:
2 years from the effective date.

Jurisdiction:
India
"""
    )


    print("\n")
    print("=" * 70)
    print("              LEGALEASE AI DOCUMENT")
    print("=" * 70)
    print("\n")

    print(document)

    print("\n")
    print("=" * 70)
    print("              END OF DOCUMENT")
    print("=" * 70)